<?php

namespace NewsFeedBundle\Repository;

/**
 * NewsFeedItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsFeedItemRepository extends \Doctrine\ORM\EntityRepository
{
}
